export const FETCH_LOCAL_WEATHER = 'FETCH_LOCAL_WEATHER';
export const SEARCH_WEATHER = 'SEARCH_WEATHER';
export const FILTER_FAVOURITES = 'FILTER_FAVOURITES';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const REMOVE_ALL_FAVOURITES = 'REMOVE_ALL_FAVOURITES';

export const FILTER_RECENTS = 'FILTER_RECENTS';
export const ADD_TO_RECENT = 'ADD_TO_RECENT';
export const REMOVE_ALL_RECENTS = 'REMOVE_ALL_RECENTS';
export const GET_RECENTS = 'GET_RECENTS';

export const SET_LOADING = 'SET_LOADING';
export const SET_UNIT = 'SET_UNIT';
export const SET_ERROR = 'SET_ERROR';
